config_version = 1
# Name of this device preset, used for lookup
name = "adafruit_mlx90614"
# Type of this preset; currently the only type is device
type = "device"

# Preset-level metadata; format follows that specified in the top-level
[metadata]
name_full = "Adafruit MLX90614 Infared Temperature Sensor"
author = "C.A.M. Gerlach"
description = "Device preset for reading the Adafruit Melexis MLX90614 I2C infared temperature sensor"
homepage = "https://www.Gerlach.CAM"
repo = "https://github.com/CAM-Gerlach"
preset_version = "0.1.0"
brokkr_version_min = "0.3.0"

# Data types referenced in individual presets
[data_types]
mlx90614_ambient_temperature = { full_name = "Ambient Temperature (MLX90614)", binary_type = "f", unit = "C", uncertainty = 0.5, custom_attrs.attribute_name = "ambient_temperature", digits = 3, range_min = -40, range_max = 125 }
mlx90614_object_temperature = { full_name = "Object Temperature (MLX90614)",  binary_type = "f", unit = "C", uncertainty = 0.5, custom_attrs.attribute_name = "object_temperature", digits = 3, range_min = -70, range_max = 380 }

# The Adafruit MLX90614 data input
[inputs.mlx90614]
_module_path = "brokkr.inputs.adafruiti2c"
_class_name = "AdafruitI2CInput"
# Dependencies required by this specific input preset
_dependencies = [ "adafruit-circuitpython-mlx90614" ]
name = "Adafruit MLX90614 Infared Temperature Sensor"
sensor_module = "adafruit_mlx90614"
sensor_class = "MLX90614"
data_types = [
    "mlx90614_ambient_temperature",
    "mlx90614_object_temperature",
]
i2c_kwargs.frequency = 100000
