config_version = 1
# Name of this device preset, used for lookup
name = "honeywell_hih6130"
# Type of this preset; currently the only type is device
type = "device"

# Preset-level metadata; format follows that specified in the top-level
[metadata]
name_full = "Honeywell HIH6130 Humidity and Temperature Sensor"
author = "C.A.M. Gerlach"
description = "Device preset for reading the Honeywell HIH6130 I2C relative humidity and temperature sensor"
homepage = "https://www.Gerlach.CAM"
repo = "https://github.com/CAM-Gerlach"
preset_version = "0.1.0"
brokkr_version_min = "0.3.0"

# Data types referenced in individual presets
[data_types]
hih6130_temperature = { full_name = "Temperature (HIH6130)", binary_type = "f", conversion = "eval", expression = "(float((value[2] << 6) + (value[3] >> 2)) / (2**14 - 1)) * 165.0 - 40", unit = "C", uncertainty = 1.0, digits = 3, range_min = -25, range_max = 85 }
hih6130_humidity = { full_name = "Humidity (HIH6130)", binary_type = "f", conversion = "eval", expression = "((value[0] & 0x3f) << 8 | value[1]) * 100.0 / (2**14 - 1)", unit = "%", uncertainty = 5.0, digits = 3, range_min = 0, range_max = 100 }

# The Honeywell HIH6130 data input
[inputs.hih6130]
_module_path = "brokkr.inputs.smbusi2c"
_class_name = "SMBusI2CBlockInput"
# Dependencies required by this specific input preset
_dependencies = [ "smbus2" ]
name = "Honeywell HIH6130 Humidity and Temperature Sensor"
i2c_addr = 0x27
register = 0
length = 4
include_all_data_each = true
data_types = [
    "hih6130_temperature",
    "hih6130_humidity",
]
